const privacySections = [
	['What we collect', 'We collect the information you choose to share, such as your name, contact details, location, skills, availability, booking details and messages. Workers may also share verification documents and work history.'],
	['Why we use it', 'Your information helps us create profiles, show nearby availability, match the right worker, confirm bookings, process payments, provide support and improve the platform.'],
	['What others can see', 'Profile information that helps people make a booking may be visible to the relevant customer, worker or business. Private contact details, documents and payment information are only shared when needed to provide the service.'],
	['Your choices', 'You can review and update your profile, manage communication preferences and ask us to correct or delete information, subject to records we need to keep for safety, payments or legal reasons.'],
	['Keeping data safe', 'We use reasonable technical and operational safeguards to protect account, booking and payment information. Please keep your password private and contact us quickly if you notice unusual activity.'],
]

function Privacy() {
	return <section className="legal-page privacy-page"><header className="legal-hero"><div><p className="eyebrow">Your information, your choice</p><h1>Privacy, made <em>clear.</em></h1><p>We collect only what helps Mazdoor Sytu connect people, manage work and keep the community safe.</p></div><div className="legal-meta"><span>LAST UPDATED</span><strong>23 September 2026</strong><small>Version 1.0</small></div></header><div className="privacy-promise"><span className="privacy-icon">✓</span><div><strong>Our promise to you</strong><p>Your information belongs to you. We use it to make work easier, safer and more relevant, not to make things confusing.</p></div></div><div className="legal-layout"><aside className="legal-summary"><span className="panel-kicker">AT A GLANCE</span><h2>Useful data. Clear choices.</h2><p>We explain what we collect, why we need it and how you can manage it.</p><a href="mailto:privacy@mazdoorSytu.in">Privacy questions ↗</a></aside><div className="legal-content"><p className="legal-intro">This policy applies to workers, households, businesses and visitors who use Mazdoor Sytu. By using the platform, you understand that information is handled as described below.</p>{privacySections.map(([title, text], index) => <article className="legal-section" key={title}><span>{String(index + 1).padStart(2, '0')}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}<div className="legal-contact"><strong>Want to know more?</strong><p>Our team can help with access, corrections or privacy requests.</p><a href="/support">Contact support ↗</a></div></div></div></section>
}

export default Privacy
